CREATE TABLE IF NOT EXISTS public.suppliers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nama TEXT NOT NULL,
	kontak TEXT,
	alamat TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.invoices (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nama_utang TEXT NOT NULL,
	supplier_id BIGINT NOT NULL REFERENCES public.suppliers(id) ON DELETE CASCADE,
	nomor_faktur TEXT NOT NULL UNIQUE,
	tanggal_faktur DATE NOT NULL,
	tanggal_jatuh_tempo DATE NOT NULL,
	total_amount NUMERIC(15, 2) NOT NULL CHECK (total_amount > 0),
	syarat_pembayaran TEXT DEFAULT '-',
	diskon_persen NUMERIC(5, 2) DEFAULT 0,
	diskon_hari INTEGER DEFAULT 0,
	net_hari INTEGER DEFAULT 0,
	keterangan TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.payments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	invoice_id BIGINT NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
	tanggal_bayar DATE NOT NULL,
	jumlah_bayar NUMERIC(15, 2) NOT NULL CHECK (jumlah_bayar > 0),
	diskon_didapat NUMERIC(15, 2) DEFAULT 0,
	denda_dikenakan NUMERIC(15, 2) DEFAULT 0,
	metode TEXT NOT NULL DEFAULT 'transfer' CHECK (metode IN ('transfer', 'tunai', 'giro', 'cek')),
	keterangan TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_metode_check;
ALTER TABLE public.payments ADD CONSTRAINT payments_metode_check
	CHECK (metode IN ('transfer', 'tunai', 'giro', 'cek'));

-- Aplikasi memakai anon key dari browser; aktifkan autentikasi dan RLS untuk data sensitif.
ALTER TABLE public.suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments DISABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.suppliers, public.invoices, public.payments TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;