-- ============================================================
-- DATABASE SCHEMA: SISTEM PENCATATAN UTANG (TOKO ELEKTRONIK MAJU)
-- ENTITAS (4 ENTITAS SCHEMAS): suppliers, products, invoices, payments
-- ============================================================

-- 1. HAPUS TABEL LAMA JIKA SUDAH ADA (AGAR TER-UPDATE DENGAN BERSIH DI SUPABASE)
DROP TABLE IF EXISTS public.activity_logs CASCADE;
DROP TABLE IF EXISTS public.payments CASCADE;
DROP TABLE IF EXISTS public.invoices CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.suppliers CASCADE;
DROP TABLE IF EXISTS public.product_categories CASCADE;

-- 2. TABEL 1: SUPPLIER (DENGAN STATUS AKTIF/NONAKTIF)
CREATE TABLE public.suppliers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nama TEXT NOT NULL,
	kontak TEXT,
	alamat TEXT,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. TABEL 2: DATA BARANG (DENGAN KATEGORI TEXT, STATUS AKTIF/NONAKTIF)
CREATE TABLE public.products (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nama TEXT NOT NULL,
	kategori TEXT DEFAULT '-',
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. TABEL 3: FAKTUR & UTANG USAHA
CREATE TABLE public.invoices (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nama_utang TEXT NOT NULL,
	product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
	supplier_id BIGINT NOT NULL REFERENCES public.suppliers(id) ON DELETE CASCADE,
	nomor_faktur TEXT NOT NULL UNIQUE,
	tanggal_faktur DATE NOT NULL,
	tanggal_jatuh_tempo DATE NOT NULL,
	total_amount NUMERIC(15, 2) NOT NULL CHECK (total_amount > 0),
	syarat_pembayaran TEXT DEFAULT '-',
	diskon_persen NUMERIC(5, 2) DEFAULT 0,
	diskon_hari INTEGER DEFAULT 0,
	net_hari INTEGER DEFAULT 0,
	keterangan TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. TABEL 4: PEMBAYARAN UTANG
CREATE TABLE public.payments (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	invoice_id BIGINT NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
	tanggal_bayar DATE NOT NULL,
	jumlah_bayar NUMERIC(15, 2) NOT NULL CHECK (jumlah_bayar > 0),
	diskon_didapat NUMERIC(15, 2) DEFAULT 0,
	denda_dikenakan NUMERIC(15, 2) DEFAULT 0,
	metode TEXT NOT NULL DEFAULT 'transfer' CHECK (metode IN ('transfer', 'tunai', 'giro', 'cek')),
	keterangan TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. NONAKTIFKAN RLS AGAR TIDAK DIBLOKIR FRONTEND BROWSER
ALTER TABLE public.suppliers     DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products      DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices      DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments      DISABLE ROW LEVEL SECURITY;

-- 7. BERIKAN HAK AKSES PERMISSIONS UTK SUPABASE ANON/AUTHENTICATED ROLE
GRANT ALL ON TABLE public.suppliers, public.products, public.invoices, public.payments TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;